version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  run-performance-tests:
    docker:
      - image: node:14
    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: npm install
      - run:
          name: "Run Performance Tests"
          command: |
            npm install -g lighthouse
            lighthouse http://localhost:3000/index.html --output json > performance-report.json
            # Agregar lógica para verificar las métricas y fallar si es necesario

workflows:
  version: 2
  say-hello-workflow:
    jobs:
      - say-hello
      - run-performance-tests:
          requires:
            - say-hello
